version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - node ./src/server/server.js
artifacts:
  files:
    - '**/*'
  base-directory: build